name: Greetings

on:
  pull_request_target:
  issues:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: >
            We're glad you're here. Before we proceed, please make sure to review and agree to our Code of Conduct, Developer Certificate of Origin (DCO), and License. Following these guidelines helps ensure a smooth collaboration process. If you have any questions or need assistance, feel free to reach out. Thanks for contributing!
          pr-message: >
            We appreciate your interest in contributing to our project. As this is your first pull request, please ensure you have followed our Contributing Guidelines, as well as our Git/GitHub workflows. Adhering to these practices helps maintain our project's quality and ease of collaboration. If you're unsure about anything or need some help, don't hesitate to ask. Happy coding!
