name: Issue Triage Labeler

on:
  issues:
    types: [opened]

jobs:
  label-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Add triage label to new issues from non-collaborators
        uses: actions/github-script@v5
        with:
          script: |
            const issueCreator = context.payload.issue.user.login;
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            // Check if the issue creator is a collaborator
            const isCollaborator = await github.rest.repos.checkCollaborator({
              owner: repoOwner,
              repo: repoName,
              username: issueCreator,
            }).then(response => true).catch(error => false);

            // If not a collaborator, add the needs review label
            if (!isCollaborator) {
              github.rest.issues.addLabels({
                owner: repoOwner,
                repo: repoName,
                issue_number: context.issue.number,
                labels: ['needs review']
              });
            }
          repo-token: ${{ secrets.GITHUB_TOKEN }}
